name: Build Android APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Android APK
        uses: pwa-builder/pwabuilder-android@v1
        with:
          siteUrl: "http://3.110.86.38:5000"
          manifestUrl: "http://3.110.86.38:5000/static/manifest.json"
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: NanoBoys-Android-App
          path: ./**/*.apk
